#!/bin/bash
# Shell Environment Optimizer
# Variant #8 - Distinct implementation with unique naming and approach

set -euo pipefail

# ============================================================================
# Configuration Constants
# ============================================================================

readonly SCRIPT_NAME="shell-env-optimizer"
readonly CONFIG_DIR="${HOME}/.config/shell"
readonly INIT_SCRIPT="${CONFIG_DIR}/init.sh"
readonly BACKUP_SUFFIX=".bak-$(date +%Y%m%d%H%M%S)"

# Shell detection
SHELL_TYPE=$(basename "$SHELL")
case "$SHELL_TYPE" in
    bash) SHELL_RC="${HOME}/.bashrc" ;;
    zsh)  SHELL_RC="${HOME}/.zshrc" ;;
    *)    SHELL_RC="${HOME}/.${SHELL_TYPE}rc";;
esac

# ============================================================================
# Utility Functions
# ============================================================================

log_info() {
    echo "[${SCRIPT_NAME}] INFO: $*"
}

log_error() {
    echo "[${SCRIPT_NAME}] ERROR: $*" >&2
}

ensure_dir() {
    local dir="$1"
    if [[ ! -d "$dir" ]]; then
        mkdir -p "$dir"
        log_info "Created directory: $dir"
    fi
}

# ============================================================================
# Initialize Configuration Directory
# ============================================================================

init_config_dir() {
    ensure_dir "$CONFIG_DIR"
    ensure_dir "${CONFIG_DIR}/functions"
    ensure_dir "${CONFIG_DIR}/aliases"
}

# ============================================================================
# Generate Init Script
# ============================================================================

generate_init_script() {
    log_info "Generating initialization script at ${INIT_SCRIPT}"
    
    cat > "${INIT_SCRIPT}" << 'INIT_SCRIPT_EOF'
#!/bin/bash
# Auto-generated Shell Environment Initialization Script
# Generated by: shell-env-optimizer (Variant #8)

# -----------------------------------------------------------------------------
# Environment Variables Configuration
# -----------------------------------------------------------------------------

# Enhanced color settings for ls
export LS_COLORS="di=01;34:ln=01;36:mf=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"

# Prompt customization variables
export PS1_CUSTOM_ENABLED=true
export PROMPT_SHOW_BRANCH=true
export PROMPT_SHOW_STATUS=true

# Path extensions
export PATH="$HOME/.local/bin:$PATH"
export MANPATH="$HOME/.local/share/man:$MANPATH"

# Editor preference
export EDITOR="${EDITOR:-vim}"
export VISUAL="${VISUAL:-vim}"

# Terminal settings
export TERM="${TERM:-xterm-256color}"

# History configuration
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups

# Time format
export TIMEFORMAT="%R real %U user %S sys\n"

# -----------------------------------------------------------------------------
# Enhanced Directory Navigation Functions
# -----------------------------------------------------------------------------

# Smart directory change with history support
smart_cd() {
    local target="$1"
    
    # If no argument, go to home
    if [[ -z "$target" ]]; then
        cd ~
        return 0
    fi
    
    # If starts with dot, navigate relative to home
    if [[ "$target" == .* ]]; then
        cd "$HOME${target}"
        return $?
    fi
    
    # Check if it's a saved directory in .dir_history
    if [[ -f "$HOME/.dir_history" ]]; then
        while IFS='=' read -r name path; do
            if [[ "$name" == "$target" ]]; then
                if [[ -d "$path" ]]; then
                    cd "$path"
                    return $?
                fi
            fi
        done < "$HOME/.dir_history"
    fi
    
    # Normal cd behavior
    cd "$target"
}

# Enhanced ls with context-aware options
enhanced_ls() {
    local use_color="--color=auto"
    local use_human="--human-readable"
    local show_size=""
    
    # Detect if we're in a git repository
    if git rev-parse --git-dir > /dev/null 2>&1; then
        show_size="-s"
    fi
    
    # Check for flags
    local has_long=false
    local has_all=false
    for arg in "$@"; do
        [[ "$arg" == "-l"* ]] && has_long=true
        [[ "$arg" == "-a"* ]] && has_all=true
    done
    
    # Build command
    if [[ "$has_long" == true ]]; then
        ls -l $use_color $use_human $show_size "$@"
    else
        ls $use_color "$@"
    fi
}

# Quick file search with context
quick_find() {
    local search_term="$1"
    local search_dir="${2:-.}"
    local max_depth="${3:-10}"
    local file_type="${4:-f}"
    
    if [[ -z "$search_term" ]]; then
        echo "Usage: quick_find <term> [directory] [max_depth] [type]"
        echo "  type: f=file, d=directory, t=both"
        return 1
    fi
    
    local find_args=()
    case "$file_type" in
        d) find_args+=("-type d") ;;
        t) ;;
        *) find_args+=("-type f") ;;
    esac
    
    find "$search_dir" -maxdepth "$max_depth" "${find_args[@]}" \
         -name "*${search_term}*" \
         -print0 2>/dev/null | \
         sort -z | \
         sed -z 's/.*/\x1b[1;34m&\x1b[0m/' | \
         tr '\0' '\n'
}

# -----------------------------------------------------------------------------
# Directory Navigation Shortcuts
# -----------------------------------------------------------------------------

# Save current directory as named shortcut
dir_save() {
    local name="$1"
    local dir="${2:-$(pwd)}"
    
    if [[ -z "$name" ]]; then
        echo "Usage: dir_save <name> [directory]"
        return 1
    fi
    
    echo "${name}=${dir}" >> "$HOME/.dir_history"
    echo "Saved: $name -> $dir"
}

# List saved directory shortcuts
dir_list() {
    if [[ -f "$HOME/.dir_history" ]]; then
        cat "$HOME/.dir_history"
    else
        echo "No saved directories"
    fi
}

# Remove saved directory shortcut
dir_rm() {
    local name="$1"
    if [[ -z "$name" ]]; then
        echo "Usage: dir_rm <name>"
        return 1
    fi
    
    local temp_file=$(mktemp)
    grep -v "^${name}=" "$HOME/.dir_history" > "$temp_file"
    mv "$temp_file" "$HOME/.dir_history"
    echo "Removed: $name"
}

# -----------------------------------------------------------------------------
# Quick File Operations
# -----------------------------------------------------------------------------

# Create directory and cd into it
mkcd() {
    mkdir -p "$1"
    cd "$1"
}

# Create file and edit it
mkedit() {
    local file="$1"
    touch "$file"
    ${EDITOR:-vim} "$file"
}

# Quick grep with context
qgrep() {
    local pattern="$1"
    local directory="${2:-.}"
    find "$directory" -type f -name "*.txt" -o -name "*.md" -o -name "*.sh" -o -name "*.py" -o -name "*.js" 2>/dev/null | \
        xargs grep -n --color=always "$pattern" 2>/dev/null
}

# -----------------------------------------------------------------------------
# Enhanced Aliases
# -----------------------------------------------------------------------------

# Command aliases
alias ll='ls -la --color=auto'
alias lsh='ls -lh --color=auto'
alias lt='ls -ltr --color=auto'
alias la='ls -A --color=auto'
alias l='ls --color=auto'

# Git aliases
alias gco='git checkout'
alias gci='git commit'
alias gsta='git status'
alias gpush='git push'
alias gpull='git pull'

# System aliases
alias dfh='df -h'
alias duh='du -h --max-depth=1'
alias freeh='free -h'

# -----------------------------------------------------------------------------
# Prompt Enhancement (if enabled)
# -----------------------------------------------------------------------------

if [[ "$PS1_CUSTOM_ENABLED" == "true" ]]; then
    set_git_branch() {
        git branch 2>/dev/null | grep '^*' | sed 's/* //'
    }
    
    preexec() {
        echo -n "→ "
    }
fi

# Export functions for subshells
export -f smart_cd enhanced_ls quick_find dir_save dir_list dir_rm mkcd mkedit qgrep
INIT_SCRIPT_EOF

    chmod +x "${INIT_SCRIPT}"
    log_info "Created: ${INIT_SCRIPT}"
}

# ============================================================================
# Update Shell Configuration
# ============================================================================

update_shell_rc() {
    log_info "Updating shell configuration: ${SHELL_RC}"
    
    # Check if already sourced
    local source_line="source \"${INIT_SCRIPT}\""
    local comment_line="# Shell Environment Optimizer - Auto-generated"
    
    if grep -q "${comment_line}" "$SHELL_RC" 2>/dev/null; then
        log_info "Configuration already exists, updating..."
        # Remove old source lines
        sed -i "/^source.*${INIT_SCRIPT}$/d" "$SHELL_RC"
        sed -i "/^source.*${INIT_SCRIPT%/}/d" "$SHELL_RC"
    else
        # Create backup
        cp "$SHELL_RC" "${SHELL_RC}${BACKUP_SUFFIX}"
        log_info "Created backup: ${SHELL_RC}${BACKUP_SUFFIX}"
    fi
    
    # Append new configuration
    {
        echo ""
        echo "${comment_line}"
        echo "${source_line}"
        echo "# End Shell Environment Optimizer"
    } >> "$SHELL_RC"
    
    log_info "Updated: ${SHELL_RC}"
}

# ============================================================================
# Main Execution
# ============================================================================

main() {
    log_info "Starting Shell Environment Optimizer (Variant #8)"
    log_info "Detected shell: ${SHELL_TYPE}"
    
    # Initialize
    init_config_dir
    
    # Generate init script
    generate_init_script
    
    # Update shell config
    update_shell_rc
    
    # Summary
    echo ""
    log_info "============================================"
    log_info "Optimization Complete!"
    log_info "============================================"
    log_info "Init script: ${INIT_SCRIPT}"
    log_info "Shell config: ${SHELL_RC}"
    echo ""
    echo "To apply changes immediately, run:"
    echo "  source ${SHELL_RC}"
    echo ""
    echo "Or restart your shell session."
}

# Run main function
main "$@"