#!/bin/bash
# Shell Environment Optimizer

# Configuration variables
CONFIG_DIR="$HOME/.config/shell"
INIT_SCRIPT="$CONFIG_DIR/init.sh"
SHELL_RC=""

# Detect shell configuration file
detect_shell_rc() {
    if [[ -n "$ZSH_NAME" ]] || [[ "$SHELL" == *"/zsh" ]]; then
        SHELL_RC="$HOME/.zshrc"
    else
        SHELL_RC="$HOME/.bashrc"
    fi
}

# Color output helpers
print_info() { echo -e "\033[1;34m[INFO]\033[0m $1"; }
print_success() { echo -e "\033[1;32m[OK]\033[0m $1"; }
print_warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }

# Create directory structure
ensure_config_dir() {
    if [[ ! -d "$CONFIG_DIR" ]]; then
        mkdir -p "$CONFIG_DIR"
        print_info "Created config directory: $CONFIG_DIR"
    fi
}

# Generate the initialization script
generate_init_script() {
    cat > "$INIT_SCRIPT" << 'INITEOF'
# ============================================
# Shell Environment Initialization Script
# Generated by Shell Environment Optimizer
# ============================================

# Color codes for enhanced output
export TERM=xterm-256color 2>/dev/null
export CLICOLOR=1

# Directory colors for ls
export LS_COLORS="di=01;34:ln=01;36:mr=40;31:ex=01;32:pi=40;33:so=01;35:do=01;32"

# History configuration
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups
export HISTTIMEFORMAT="%F %T "

# Prompt customization variables
export PS1_COLOR="\[\033[0;36m\]"
export PS1_RESET="\[\033[0m\]"

# ============================================
# Enhanced Functions
# ============================================

# enhanced_ls - Colored, human-readable directory listings with tree structure
enhanced_ls() {
    local dir="${1:-.}"
    
    if [[ -d "$dir" ]]; then
        if command -v exa >/dev/null 2>&1; then
            exa --tree --icons --color=always --level=1 "$dir"
        elif command -v lsd >/dev/null 2>&1; then
            lsd --tree --icons --color=always --level=1 "$dir"
        else
            echo "=== Directory: $dir ==="
            printf "\033[1;34m%-30s\033[0m %10s %s\n" "NAME" "SIZE" "MODIFIED"
            printf "%-30s %10s %s\n" "----" "----" "-------"
            ls -lh --time-style=long-iso "$dir" 2>/dev/null | \
                awk '{printf "\033[1;34m%-30s\033[0m %10s %s\n", $9, $5, $6}'
        fi
    else
        echo "Error: '$dir' is not a directory" >&2
        return 1
    fi
}

# smart_cd - Intelligent directory navigation with fuzzy matching
smart_cd() {
    local target="$1"
    local matches
    
    if [[ -z "$target" ]]; then
        cd "$HOME"
        return 0
    fi
    
    # Check if exact path exists
    if [[ -d "$target" ]]; then
        cd "$target"
        return 0
    fi
    
    # Check if it's a relative path from home
    if [[ -d "$HOME/$target" ]]; then
        cd "$HOME/$target"
        return 0
    fi
    
    # Fuzzy match in common directories
    local search_paths=("$HOME" "$HOME/projects" "$HOME/Downloads" "/var/www")
    
    for path in "${search_paths[@]}"; do
        if [[ -d "$path" ]]; then
            matches=$(find "$path" -maxdepth 2 -type d -iname "*$target*" 2>/dev/null | head -5)
            if [[ -n "$matches" ]]; then
                local count=$(echo "$matches" | wc -l)
                if [[ $count -eq 1 ]]; then
                    cd "$matches"
                    echo "Smart match: $matches"
                    return 0
                else
                    echo "Multiple matches found:"
                    echo "$matches" | nl
                    echo -n "Enter number (1-$count) or q to quit: "
                    read choice
                    if [[ "$choice" =~ ^[0-9]+$ ]] && [[ $choice -le $count ]]; then
                        cd "$(echo "$matches" | sed -n "${choice}p")"
                        return 0
                    else
                        return 1
                    fi
                fi
            fi
        fi
    done
    
    echo "smart_cd: No matching directory found for '$target'" >&2
    return 1
}

# quick_find - Fast file search with preview
quick_find() {
    local search_term="$1"
    local search_dir="${2:-.}"
    local max_results="${3:-10}"
    
    if [[ -z "$search_term" ]]; then
        echo "Usage: quick_find <pattern> [directory] [max_results]"
        return 1
    fi
    
    echo "=== Searching for: $search_term ==="
    echo "Directory: $search_dir"
    echo "Max results: $max_results"
    echo "----------------------------------------"
    
    if command -v fd >/dev/null 2>&1; then
        fd --color=always --type f "$search_term" "$search_dir" | head -n "$max_results"
    elif command -v find >/dev/null 2>&1; then
        find "$search_dir" -type f -iname "*$search_term*" 2>/dev/null | head -n "$max_results"
    fi
    
    local count=$(find "$search_dir" -type f -iname "*$search_term*" 2>/dev/null | wc -l)
    echo "----------------------------------------"
    echo "Total matches: $count"
}

# ============================================
# Helper Functions
# ============================================

# quick_grep - Grep with context and line numbers
quick_grep() {
    local pattern="$1"
    shift
    grep --color=always -n -H -r -I --exclude-dir={.git,node_modules,vendor} "$pattern" "$@"
}

# quick_cat - Cat with line numbers and syntax highlighting
quick_cat() {
    local file="$1"
    if [[ -f "$file" ]]; then
        if command -v bat >/dev/null 2>&1; then
            bat --line-number --style=plain "$file"
        else
            cat -n "$file"
        fi
    else
        echo "File not found: $file" >&2
        return 1
    fi
}

# ============================================
# Aliases
# ============================================

# System aliases
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -ltr'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gb='git branch'
alias gd='git diff'
alias gco='git checkout'

# File operation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias h='cd ~'

# ============================================
# Completion Setup
# ============================================

if [[ "$SHELL" == *"/bash" ]]; then
    complete -o filenames -C /usr/lib/git-core/git-completion.bash git 2>/dev/null || true
fi
INITEOF
    
    chmod +x "$INIT_SCRIPT"
    print_success "Generated initialization script: $INIT_SCRIPT"
}

# Update shell configuration
update_shell_rc() {
    detect_shell_rc
    
    # Check if already sourced
    if grep -q "source.*shell/init.sh" "$SHELL_RC" 2>/dev/null; then
        print_warn "Shell config already sources the init script"
        return 0
    fi
    
    # Add source command
    echo "" >> "$SHELL_RC"
    echo "# Shell Environment Optimizer" >> "$SHELL_RC"
    echo "if [[ -f ~/.config/shell/init.sh ]]; then" >> "$SHELL_RC"
    echo "    source ~/.config/shell/init.sh" >> "$SHELL_RC"
    echo "fi" >> "$SHELL_RC"
    
    print_success "Updated shell config: $SHELL_RC"
}

# Main execution
main() {
    echo "========================================"
    echo "  Shell Environment Optimizer"
    echo "========================================"
    echo ""
    
    ensure_config_dir
    generate_init_script
    update_shell_rc
    
    echo ""
    echo "========================================"
    print_success "Shell environment optimization complete!"
    echo ""
    echo "To apply changes, run one of:"
    echo "  • source ~/.bashrc   (for bash)"
    echo "  • source ~/.zshrc    (for zsh)"
    echo "  • Or start a new shell session"
    echo ""
    echo "Available commands:"
    echo "  • enhanced_ls [dir]  - Enhanced directory listing"
    echo "  • smart_cd <dir>     - Smart directory navigation"
    echo "  • quick_find <term>  - Fast file search"
}

main "$@"