#!/bin/bash
# Shell Environment Optimizer

set -euo pipefail

# Configuration variables
readonly CONFIG_DIR="${HOME}/.config/shell"
readonly INIT_SCRIPT="${CONFIG_DIR}/init.sh"
readonly SHELL_RC="${SHELL##*/}"
readonly SHELL_RC_PATH="${HOME}/.${SHELL_RC}rc"

# Colors for output
readonly CYAN='\033[0;36m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m' # No Color

log_info() { echo -e "${CYAN}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

# Function to check if we're running interactively
is_interactive() {
    [[ $- == *i* ]]
}

# Enhanced ls function with color and auto-flags
enhanced_ls() {
    if [[ $# -eq 0 ]]; then
        local flags="-laF --color=auto"
        [[ -t 1 ]] || flags="--color=never"
        command ls $flags "$@"
    else
        command ls -F --color=auto "$@"
    fi
}

# Smart cd with fuzzy matching and shortcuts
smart_cd() {
    local target="$1"
    
    # Special shortcuts
    case "$target" in
        "p"|"prev") cd - ;;
        "u"|"up") cd .. ;;
        "h"|"home") cd "$HOME" ;;
        "d"|"down") cd "$HOME/Downloads" ;;
    esac
    
    # Fuzzy search in path
    if [[ -z "$target" || ! -d "$target" ]]; then
        local match=$(cd "$HOME" 2>/dev/null && ls -d */ | fzf --query="$target" 2>/dev/null | sed 's/\/$//')
        if [[ -n "$match" ]]; then
            cd "$match"
        else
            echo "Directory not found: $target" >&2
            return 1
        fi
    fi
}

# Quick find with preview
quick_find() {
    local name="$1"
    shift
    local path="${1:-$HOME}"
    
    find "$path" -type f -name "*${name}*" 2>/dev/null | head -20
}

# Setup directories
setup_directories() {
    log_info "Setting up configuration directories..."
    mkdir -p "$CONFIG_DIR"
    log_success "Created ${CONFIG_DIR}"
}

# Create initialization script
create_init_script() {
    log_info "Creating initialization script at ${INIT_SCRIPT}..."
    
    cat > "$INIT_SCRIPT" << 'INIT_EOF'
# Shell Environment Optimizer - Init Script
# Generated by Shell Environment Optimizer

# Enhanced ls function
enhanced_ls() {
    if [[ $# -eq 0 ]]; then
        local flags="-laF --color=auto"
        [[ -t 1 ]] || flags="--color=never"
        command ls $flags "$@"
    else
        command ls -F --color=auto "$@"
    fi
}

# Smart cd with fuzzy matching
smart_cd() {
    local target="$1"
    case "$target" in
        "p"|"prev") cd - ;;
        "u"|"up") cd .. ;;
        "h"|"home") cd "$HOME" ;;
        "d"|"down") cd "$HOME/Downloads" ;;
    esac
    if [[ -z "$target" || ! -d "$target" ]]; then
        local match=$(cd "$HOME" 2>/dev/null && ls -d */ | fzf --query="$target" 2>/dev/null | sed 's/\/$//')
        if [[ -n "$match" ]]; then
            cd "$match"
        else
            echo "Directory not found: $target" >&2
            return 1
        fi
    fi
}

# Quick find with preview
quick_find() {
    local name="$1"
    shift
    local path="${1:-$HOME}"
    find "$path" -type f -name "*${name}*" 2>/dev/null | head -20
}

# Environment variables
export EDITOR="${EDITOR:-vim}"
export LESS="-RfX"
export PAGER="less"
export HISTCONTROL=ignorespace:erasedups
export HISTSIZE=10000
export HISTFILESIZE=20000

# Aliases
alias ll="enhanced_ls"
alias la="enhanced_ls -a"
alias lS="enhanced_ls -S"
alias lt="enhanced_ls -t"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
INIT_EOF
    
    log_success "Created ${INIT_SCRIPT}"
}

# Update shell rc file
update_shell_rc() {
    log_info "Updating ${SHELL_RC_PATH}..."
    
    local init_source_line="source \"${INIT_SCRIPT}\""
    
    if ! grep -q "source.*${INIT_SCRIPT}" "$SHELL_RC_PATH" 2>/dev/null; then
        echo "" >> "$SHELL_RC_PATH"
        echo "# Shell Environment Optimizer" >> "$SHELL_RC_PATH"
        echo "$init_source_line" >> "$SHELL_RC_PATH"
        log_success "Added source line to ${SHELL_RC_PATH}"
    else
        log_warn "Shell config already sources ${INIT_SCRIPT}"
    fi
}

# Main execution
main() {
    local start_time=$(date +%s)
    
    log_info "=== Shell Environment Optimizer ==="
    log_info "Shell: ${SHELL}"
    log_info "Home: ${HOME}"
    
    setup_directories
    create_init_script
    update_shell_rc
    
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    
    echo ""
    log_success "Optimization complete! (${duration}s)"
    log_info "Run 'source ${SHELL_RC_PATH}' or start a new shell to apply changes."
    
    # If running interactively, source the init script immediately
    if is_interactive; then
        if [[ -f "$INIT_SCRIPT" ]]; then
            source "$INIT_SCRIPT"
            log_success "Changes applied to current session."
        fi
    fi
}

# Run main function
main "$@"