#!/bin/bash
# Shell Environment Optimizer

# Configuration
SHELL_CONFIG_DIR="$HOME/.config/shell"
INIT_SCRIPT="$SHELL_CONFIG_DIR/init.sh"
CONFIG_FILE=""

# Detect shell type and set config file
detect_shell_config() {
    case "$SHELL" in
        *bash*)
            CONFIG_FILE="$HOME/.bashrc"
            ;;
        *zsh*)
            CONFIG_FILE="$HOME/.zshrc"
            ;;
        *)
            CONFIG_FILE="$HOME/.profile"
            ;;
    esac
    
    # Create config file if it doesn't exist
    if [[ ! -f "$CONFIG_FILE" ]]; then
        touch "$CONFIG_FILE"
    fi
}

# Create directory structure
create_config_directory() {
    mkdir -p "$SHELL_CONFIG_DIR"
    echo "Created configuration directory: $SHELL_CONFIG_DIR"
}

# Generate the initialization script
generate_init_script() {
    cat > "$INIT_SCRIPT" << 'EOF'
#!/bin/bash
# Shell Environment Initialization Script
# Auto-generated by Shell Environment Optimizer

# ============================================================================
# ENVIRONMENT VARIABLES
# ============================================================================

# Color output for better readability
export CLICOLOR=1
export TERM=xterm-256color

# Editor preference
export EDITOR=vim
export VISUAL=vim

# Pager for long outputs
export PAGER=less
export LESS="-R"

# History configuration
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth:erasedups
export HISTTIMEFORMAT="%F %T "

# Path modifications
export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/opt/libtool/bin:$PATH"

# Git configuration
export GIT_EDITOR=vim

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Enhanced ls command with color and human-readable sizes
enhanced_ls() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        command ls -G --color=auto "$@"
    else
        # Linux
        command ls --color=auto -h "$@"
    fi
}

# Smart cd - navigate without typing full path
smart_cd() {
    local input="$1"
    
    # Directories in current directory
    if [[ -d "$input" ]]; then
        cd "$input"
        return 0
    fi
    
    # Search in $PATH directories
    local dir
    for dir in $(echo $PATH | tr ':' ' '); do
        if [[ -d "$dir/$input" ]]; then
            cd "$dir/$input"
            return 0
        fi
    done
    
    # Find directory starting with input
    local found
    found=$(find ~ -maxdepth 5 -type d -name "$input"* 2>/dev/null | head -1)
    if [[ -n "$found" && -d "$found" ]]; then
        cd "$found"
        return 0
    fi
    
    # Search in parent directories
    found=$(find . -maxdepth 5 -type d -name "$input"* 2>/dev/null | head -1)
    if [[ -n "$found" && -d "$found" ]]; then
        cd "$found"
        return 0
    fi
    
    echo "smart_cd: directory not found: $input" >&2
    return 1
}

# Quick find - enhanced find with grep
quick_find() {
    local search_term="$1"
    local search_path="${2:-.}"
    local max_depth="${3:-5}"
    
    find "$search_path" -maxdepth "$max_depth" -type f -name "*$search_term*" 2>/dev/null | \
        grep -v ".git/" | \
        sed "s|$search_path/||"
}

# Quick grep - search in files with context
quick_grep() {
    local pattern="$1"
    local search_path="${2:-.}"
    
    grep -r --include="*.{sh,py,js,rb,go,c,cpp,h,hpp}" --color=always \
        -n --exclude-dir={.git,node_modules,vendor} \
        "$pattern" "$search_path" 2>/dev/null
}

# Quick tree - display directory structure
quick_tree() {
    local max_depth="${1:-3}"
    
    find . -maxdepth "$max_depth" -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
}

# Quick mkdir - create nested directories with entry
quick_mkdir() {
    local dir_name="$1"
    mkdir -p "$dir_name"
    cd "$dir_name" || return 1
    echo "Created and entered: $dir_name"
}

# Quick cd - jump to home directories
quick_cd() {
    local dir="${1:-~}"
    cd "$dir" || return 1
}

# ============================================================================
# ALIASES
# ============================================================================

# Directory listing aliases
alias ll='enhanced_ls -laF'
alias lt='enhanced_ls -laF --time-style=long-iso'
alias l='enhanced_ls -CF'
alias la='enhanced_ls -A'
alias lS='enhanced_ls -S'
alias lr='enhanced_ls -r'
alias lc='enhanced_ls -c'
alias lg='enhanced_ls -g'

# File system aliases
alias df='df -h'
alias du='du -h'
alias free='free -h'

# Network aliases
alias ip='ip addr show'
alias ping='ping -c 4'
alias dig='dig +short'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gl='git pull'
alias gb='git branch'
alias gd='git diff'
alias gco='git checkout'
alias gm='git merge'
alias glog='git log --oneline --graph --decorate'

# System administration aliases
alias sudo='sudo '
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias mkdir='mkdir -pv'

# Archive aliases
alias tar='tar -cvzf'
alias tarx='tar -xvzf'
alias zip='zip -r'
alias unzip='unzip -o'

# Process management aliases
alias top='top -b'
alias ps='ps auxf'
alias killall='killall -i'

# ============================================================================
# PROMPT CONFIGURATION
# ============================================================================

# Enhanced PS1 with branch, path, and status
setup_prompt() {
    if [[ "$TERM" != "dumb" ]]; then
        export PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\[\e[1;36m\]$(__git_ps1 " (%s)")\[\e[0m\]\n\[\e[1;33m\]$\[\e[0m\] '
    fi
}

# Git prompt function
__git_ps1() {
    local branch
    branch=$(git symbolic-ref --short HEAD 2>/dev/null)
    if [[ $? -eq 0 && -n "$branch" ]]; then
        echo "$1" | sed "s/%s/$branch/"
    fi
}

# ============================================================================
# KEY BINDINGS
# ============================================================================

setup_keybindings() {
    # Enable autocomplete
    if [[ -d /etc/bash_completion.d ]]; then
        source /etc/bash_completion 2>/dev/null || true
    fi
    
    # Custom bindings
    bind 'set complete-ignore-case on' 2>/dev/null || true
    bind 'set show-all-if-ambiguous on' 2>/dev/null || true
    bind 'set show-all-if-unmodified on' 2>/dev/null || true
}

# ============================================================================
# INITIALIZATION
# ============================================================================

# Run initialization
setup_prompt
setup_keybindings

# Export functions
export -f enhanced_ls
export -f smart_cd
export -f quick_find
export -f quick_grep
export -f quick_tree
export -f quick_mkdir
export -f quick_cd
EOF

    chmod +x "$INIT_SCRIPT"
    echo "Generated initialization script: $INIT_SCRIPT"
}

# Update shell configuration
update_shell_config() {
    # Check if init script is already sourced
    if grep -q "sourcing $INIT_SCRIPT" "$CONFIG_FILE" 2>/dev/null; then
        echo "Shell configuration already updated."
        return 0
    fi
    
    # Add sourcing line to shell config
    echo "" >> "$CONFIG_FILE"
    echo "# ==============================================================================" >> "$CONFIG_FILE"
    echo "# Shell Environment Optimizer - Auto-generated" >> "$CONFIG_FILE"
    echo "# ==============================================================================" >> "$CONFIG_FILE"
    echo "if [[ -f \"$INIT_SCRIPT\" ]]; then" >> "$CONFIG_FILE"
    echo "    source \"$INIT_SCRIPT\"" >> "$CONFIG_FILE"
    echo "fi" >> "$CONFIG_FILE"
    
    echo "Updated shell configuration: $CONFIG_FILE"
}

# Main execution
main() {
    echo "=============================================="
    echo "  Shell Environment Optimizer"
    echo "=============================================="
    echo ""
    
    detect_shell_config
    create_config_directory
    generate_init_script
    update_shell_config
    
    echo ""
    echo "=============================================="
    echo "  Optimization Complete!"
    echo "=============================================="
    echo ""
    echo "To apply changes immediately, run:"
    echo "  source $CONFIG_FILE"
    echo ""
    echo "Or start a new shell session."
    echo ""
}

# Run main function
main "$@"