#!/bin/bash
# Shell Environment Optimizer

# =============================================================================
# Configuration Variables
# =============================================================================

readonly CONFIG_DIR="$HOME/.config/shell"
readonly INIT_SCRIPT="$CONFIG_DIR/init.sh"
readonly MARKER="# === SHELL ENVIRONMENT OPTIMIZER BEGINS ==="
readonly MARKER_END="# === SHELL ENVIRONMENT OPTIMIZER ENDS ==="

# Color codes for enhanced output
declare -A COLORS=(
    [blue]='\033[0;34m'
    [green]='\033[0;32m'
    [yellow]='\033[0;33m'
    [red]='\033[0;31m'
    [bold]='\033[1m'
    [reset]='\033[0m'
)

# =============================================================================
# Core Functions
# =============================================================================

enhanced_ls() {
    local dir="${1:-.}"
    local size_display="${2:-human}"
    
    if command -v exa &>/dev/null; then
        exa --icons --git --color=always --group-directories-first "$@"
    elif command -v ls &>/dev/null; then
        if [[ $size_display == "human" ]]; then
            ls -lah --color=always --group-directories-first "$@"
        else
            ls -la --color=always --group-directories-first "$@"
        fi
    else
        echo "${COLORS[red]}No listing command found${COLORS[reset]}"
    fi
}

smart_cd() {
    local target="$1"
    local cache_file="$CONFIG_DIR/.cd_history"
    
    # Create cache directory if needed
    mkdir -p "$CONFIG_DIR" 2>/dev/null
    
    if [[ -z "$target" ]]; then
        cd ~
        return
    fi
    
    # Check if path exists
    if [[ -d "$target" ]]; then
        cd "$target"
        return
    fi
    
    # Search in history cache
    if [[ -f "$cache_file" ]]; then
        local cached_path
        cached_path=$(grep "^${target}:" "$cache_file" | head -1 | cut -d':' -f2)
        if [[ -n "$cached_path" && -d "$cached_path" ]]; then
            cd "$cached_path"
            return
        fi
    fi
    
    # Check $PATH directories
    for path_dir in ${PATH//:/ }; do
        if [[ -d "$path_dir/$target" ]]; then
            cd "$path_dir/$target"
            return
        fi
    done
    
    echo "${COLORS[yellow]}Directory '$target' not found${COLORS[reset]}"
    return 1
}

quick_find() {
    local search_term="$1"
    local search_dir="${2:-.}"
    local max_depth="${3:-5}"
    
    if [[ -z "$search_term" ]]; then
        echo "${COLORS[yellow]}Usage: qfind <pattern> [directory] [max-depth]${COLORS[reset]}"
        return 1
    fi
    
    find "$search_dir" -maxdepth "$max_depth" -type f -name "*$search_term*" 2>/dev/null | \
        while IFS= read -r filepath; do
            local rel_path="${filepath#./}"
            local dir_part
            local file_part
            dir_part=$(dirname "$rel_path")
            file_part=$(basename "$rel_path")
            
            # Highlight match
            local highlighted
            highlighted=$(echo "$file_part" | sed -E "s/($search_term)/${COLORS[bold]}\1${COLORS[reset]}/g")
            
            if [[ "$dir_part" == "." ]]; then
                echo -e "${COLORS[green]}$highlighted${COLORS[reset]}"
            else
                echo -e "${COLORS[blue]}$dir_part/${COLORS[green]}$highlighted${COLORS[reset]}"
            fi
        done
}

# =============================================================================
# Setup Functions
# =============================================================================

detect_shell_config() {
    local shell_name="${SHELL##*/}"
    case "$shell_name" in
        zsh)
            echo "$HOME/.zshrc"
            ;;
        bash)
            echo "$HOME/.bashrc"
            ;;
        *)
            if [[ -f "$HOME/.bashrc" ]]; then
                echo "$HOME/.bashrc"
            elif [[ -f "$HOME/.zshrc" ]]; then
                echo "$HOME/.zshrc"
            else
                echo "$HOME/.bashrc"
            fi
            ;;
    esac
}

backup_config() {
    local config_file="$1"
    local backup_file="${config_file}.backup.$(date +%Y%m%d%H%M%S)"
    
    if [[ -f "$config_file" ]]; then
        cp "$config_file" "$backup_file"
        echo "Backed up: $config_file -> $backup_file"
    fi
}

generate_init_script() {
    cat > "$INIT_SCRIPT" << 'ENDINIT'
# Shell Environment Initialization Script
# Auto-generated by Shell Environment Optimizer

# Enhanced Directory Listing with Colors and Icons
function enhanced_ls() {
    local dir="${1:-.}"
    local size_display="${2:-human}"
    
    if command -v exa &>/dev/null; then
        exa --icons --git --color=always --group-directories-first "$@"
    elif command -v ls &>/dev/null; then
        if [[ $size_display == "human" ]]; then
            ls -lah --color=always --group-directories-first "$@"
        else
            ls -la --color=always --group-directories-first "$@"
        fi
    else
        echo -e "\033[0;31mNo listing command found\033[0m"
    fi
}

# Intelligent Directory Navigation
function smart_cd() {
    local target="$1"
    local cache_file="$HOME/.config/shell/.cd_history"
    
    mkdir -p "$HOME/.config/shell" 2>/dev/null
    
    if [[ -z "$target" ]]; then
        cd ~
        return
    fi
    
    if [[ -d "$target" ]]; then
        cd "$target"
        return
    fi
    
    if [[ -f "$cache_file" ]]; then
        local cached_path
        cached_path=$(grep "^${target}:" "$cache_file" | head -1 | cut -d':' -f2)
        if [[ -n "$cached_path" && -d "$cached_path" ]]; then
            cd "$cached_path"
            return
        fi
    fi
    
    for path_dir in ${PATH//:/ }; do
        if [[ -d "$path_dir/$target" ]]; then
            cd "$path_dir/$target"
            return
        fi
    done
    
    echo -e "\033[0;33mDirectory '$target' not found\033[0m"
    return 1
}

# Fast File Search with Fuzzy Matching
function quick_find() {
    local search_term="$1"
    local search_dir="${2:-.}"
    local max_depth="${3:-5}"
    
    if [[ -z "$search_term" ]]; then
        echo -e "\033[0;33mUsage: qfind <pattern> [directory] [max-depth]\033[0m"
        return 1
    fi
    
    find "$search_dir" -maxdepth "$max_depth" -type f -name "*$search_term*" 2>/dev/null | \
        while IFS= read -r filepath; do
            local rel_path="${filepath#./}"
            local dir_part file_part
            dir_part=$(dirname "$rel_path")
            file_part=$(basename "$rel_path")
            
            local highlighted
            highlighted=$(echo "$file_part" | sed -E "s/($search_term)/\033[1m\1\033[0m/g")
            
            if [[ "$dir_part" == "." ]]; then
                echo -e "\033[0;32m$highlighted\033[0m"
            else
                echo -e "\033[0;34m$dir_part/\033[0;32m$highlighted\033[0m"
            fi
        done
}

# Environment Variables
export EDITOR="${EDITOR:-nano}"
export VISUAL="${VISUAL:-nano}"
export PAGER="${PAGER:-less}"
export LESS="-RFX"
export HISTSIZE=10000
export HISTFILESIZE=20000
export SAVEHIST="$HISTSIZE"
export HISTCONTROL=ignoredups:ignorespace
export PATH="$HOME/.local/bin:$PATH"
export MANPAGER="less -R"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

# Prompts for interactive shells
if [[ -n "$PS1" ]]; then
    export PS1="\[\033[0;34m\]\u@\h\[\033[0m\]:\[\033[0;32m\]\w\[\033[0m\]\$ "
fi

# Aliases
alias ll='enhanced_ls -l'
alias la='enhanced_ls -a'
alias lt='enhanced_ls -t'
alias lS='enhanced_ls -S'
alias lsr='enhanced_ls -R'
alias lsd='enhanced_ls -d'
alias lg='enhanced_ls -g'
alias lG='enhanced_ls --group-directories-first'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias cd='smart_cd'
alias qfind='quick_find'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias top='top -b -n 1'
alias mkdir='mkdir -pv'
ENDINIT
    
    chmod +x "$INIT_SCRIPT"
}

modify_shell_config() {
    local config_file="$1"
    local init_script_line="source \"$INIT_SCRIPT\""
    
    # Create config directory
    mkdir -p "$CONFIG_DIR" 2>/dev/null
    
    # Check if already configured
    if grep -q "$MARKER" "$config_file" 2>/dev/null; then
        echo "Already configured. Updating..."
        # Remove old section
        sed -i "/$MARKER/,/$MARKER_END/d" "$config_file"
    fi
    
    # Append new section
    cat >> "$config_file" << ENDSECTION
$MARKER
# Settings added by Shell Environment Optimizer
$init_script_line
$MARKER_END
ENDSECTION
    
    echo "Modified: $config_file"
}

# =============================================================================
# Main Execution
# =============================================================================

main() {
    echo "=============================================="
    echo "   Shell Environment Optimizer"
    echo "=============================================="
    echo
    
    # Detect shell configuration file
    local shell_config
    shell_config=$(detect_shell_config)
    echo "Detected shell config: $shell_config"
    
    # Backup existing configuration
    backup_config "$shell_config"
    
    # Generate initialization script
    echo "Creating initialization script: $INIT_SCRIPT"
    generate_init_script
    
    # Modify shell configuration
    echo "Updating shell configuration..."
    modify_shell_config "$shell_config"
    
    echo
    echo "=============================================="
    echo "   Optimization Complete!"
    echo "=============================================="
    echo
    echo "New features available:"
    echo "  • enhanced_ls  - Improved directory listing"
    echo "  • smart_cd     - Smart directory navigation"  
    echo "  • quick_find   - Fast file search (qfind)"
    echo
    echo "Aliases added:"
    echo "  • ll, la, lt, lS - Enhanced ls variants"
    echo "  • .., ..., .... - Quick parent navigation"
    echo "  • df, du, free - Human-readable output"
    echo
    echo "To apply changes, run: source $shell_config"
    echo "Or start a new shell session."
}

# Run main function
main "$@"