#!/bin/bash
# Shell Environment Optimizer

# =============================================================================
# Configuration and Constants
# =============================================================================
readonly CONFIG_DIR="$HOME/.config/shell"
readonly INIT_SCRIPT="$CONFIG_DIR/init.sh"
readonly SHELL_CONFIG_FILE="$HOME/.bashrc"
readonly BACKUP_SUFFIX=".bak.$(date +%Y%m%d%H%M%S)"

# Color codes for output
readonly COLOUR_RESET="\033[0m"
readonly COLOUR_GREEN="\033[0;32m"
readonly COLOUR_YELLOW="\033[0;33m"
readonly COLOUR_BLUE="\033[0;34m"
readonly COLOUR_RED="\033[0;31m"

# =============================================================================
# Helper Functions
# =============================================================================

info() {
    echo -e "${COLOUR_BLUE}[INFO]${COLOUR_RESET} $1"
}

success() {
    echo -e "${COLOUR_GREEN}[SUCCESS]${COLOUR_RESET} $1"
}

warn() {
    echo -e "${COLOUR_YELLOW}[WARN]${COLOUR_RESET} $1"
}

error() {
    echo -e "${COLOUR_RED}[ERROR]${COLOUR_RESET} $1" >&2
}

# =============================================================================
# Core Functionality - Will be added to init.sh
# =============================================================================

generate_init_script() {
    local script_content="#!/bin/bash
# Auto-generated by Shell Environment Optimizer
# Created: $(date -Iseconds)

# -----------------------------------------------------------------------------
# Enhanced Listing Function
# -----------------------------------------------------------------------------
enhanced_ls() {
    local dir=\"\$1\"
    if [[ -z \"\$dir\" ]]; then
        dir=\".\"
    fi
    
    if [[ ! -d \"\$dir\" ]]; then
        echo \"Error: \${dir} is not a directory\" >&2
        return 1
    fi
    
    echo -e \"${COLOUR_BLUE}Directory: ${dir}${COLOUR_RESET}\"
    echo \"===================================================\"
    
    # List files with details
    ls -lh --color=always \"\$dir\" 2>/dev/null | \
        awk '{
            if (NF > 8) {
                printf \"%s\t%s\t%s\t%s\t%s\t%s\\n\", \$1, \$2, \$3, \$4, \$5, \$6
            } else {
                print \$0
            }
        }'
    
    echo \"\"
    echo \"--- Summary ---\"
    local total_files=\$(find \"\$dir\" -maxdepth 1 -type f | wc -l)
    local total_dirs=\$(find \"\$dir\" -maxdepth 1 -type d ! -name \".\" | wc -l)
    echo \"Files: \${total_files} | Directories: \${total_dirs}\"
}

# -----------------------------------------------------------------------------
# Smart CD Function with Fuzzy Matching
# -----------------------------------------------------------------------------
smart_cd() {
    local input=\"\$1\"
    
    if [[ -z \"\$input\" ]]; then
        cd ~
        return 0
    fi
    
    # Handle relative paths with shortcuts
    case \"\$input\" in
        ..*)
            cd \"\$input\"
            return \$?
            ;;
    esac
    
    # Check if path exists directly
    if [[ -d \"\$input\" ]]; then
        cd \"\$input\"
        return \$?
    fi
    
    # Fuzzy search in current directory and home
    local matches=(\"$(compgen -d \"\$input\")\")
    
    if [[ \${#matches[@]} -eq 1 ]]; then
        cd \"\${matches[0]}\"
        return \$?
    elif [[ \${#matches[@]} -gt 1 ]]; then
        echo \"Multiple matches found:\"
        printf \"  %s\\n\" \"\${matches[@]}\"
        return 1
    fi
    
    # Search in home directory
    local home_matches=(\"$(compgen -d \"~/\$input\")\")
    
    if [[ \${#home_matches[@]} -eq 1 ]]; then
        cd \"\${home_matches[0]}\"
        return \$?
    elif [[ \${#home_matches[@]} -gt 1 ]]; then
        echo \"Multiple matches in home:\"
        printf \"  %s\\n\" \"\${home_matches[@]}\"
        return 1
    fi
    
    echo \"Directory not found: \$input\" >&2
    return 1
}

# -----------------------------------------------------------------------------
# Quick Find Function with Preview
# -----------------------------------------------------------------------------
quick_find() {
    local search_term=\"\$1\"
    local search_path=\"\$2\"
    local max_results=\"\${3:-10}\"
    
    if [[ -z \"\$search_term\" ]]; then
        echo \"Usage: quick_find <pattern> [path] [max_results]\"
        echo \"Example: quick_find .js /home 20\"
        return 1
    fi
    
    if [[ -z \"\$search_path\" ]]; then
        search_path=\".\"
    fi
    
    echo -e \"${COLOUR_YELLOW}Searching for: \${search_term} in \${search_path}${COLOUR_RESET}\"
    echo \"---------------------------------------------------\"
    
    find \"\$search_path\" -name \"*\${search_term}*\" -type f 2>/dev/null | \
        head -n \"\$max_results\" | \
        while read -r file; do
            local rel_path=\${file#\"\$HOME/\"}
            rel_path=\${rel_path#./}
            echo -e \"${COLOUR_GREEN}\${rel_path}${COLOUR_RESET}\"
        done
}

# -----------------------------------------------------------------------------
# Additional Utility Functions
# -----------------------------------------------------------------------------

# Quick directory creation with cd
qmkcd() {
    if [[ -z \"\$1\" ]]; then
        echo \"Usage: qmkcd <directory_name>\"
        return 1
    fi
    mkdir -p \"\$1\" && cd \"\$1\" && echo \"Created and entered: \$1\"
}

# File tree viewer (lightweight)
ftree() {
    local dir=\"\${1:-.}\"
    find \"\$dir\" -maxdepth 3 -print | \
        sed -e 's/[^-][^\\/]*/\\t&/' | \
        sed -e ':a' -e 'N' -e '$!ba' -e 's/\\n/\\n    /g'
}

# Quick grep with context
qgrep() {
    if [[ -z \"\$1\" ]]; then
        echo \"Usage: qgrep <pattern> [files...]\"
        return 1
    fi
    grep -rn --color=always \"\$1\" \"\${@:2:.}\"
}

# =============================================================================
# Aliases Configuration
# =============================================================================

# File operations
alias ll='ls -alF --color=auto'
alias l='ls -CF --color=auto'
alias la='ls -A --color=auto'
alias lS='ls -lSrh --color=auto'
alias lt='ls -ltrh --color=auto'

# Git shortcuts
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph'

# System utilities
alias h='history'
alias j='jobs -l'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# =============================================================================
# Environment Variables
# =============================================================================

# Enhanced prompt variables
export PROMPT_COMMAND='${PROMPT_COMMAND:+$PROMPT_COMMAND\\;}__bash_env_update'
export CLICOLOR=1
export LSCOLORS='ExFxBxDxCxegedabagacad'

# Editor preferences
export EDITOR=\"${EDITOR:-nano}\"
export VISUAL=\"${VISUAL:-nano}\"

# Pager settings
export PAGER=\"${PAGER:-less}\"
export LESS=\"-RfX\"

# Timezone and locale
export TZ=\"${TZ:-UTC}\"
export LANG=\"${LANG:-en_US.UTF-8}\"
export LC_ALL=\"${LC_ALL:-en_US.UTF-8}\"

# =============================================================================
# Completion Functions (if available)
# =============================================================================

if [[ -n \"\$BASH_COMPLETION_VERSION\" ]]; then
    complete -f qmkcd
    complete -f qgrep
fi

echo -e \"${COLOUR_GREEN}Shell environment initialized successfully!${COLOUR_RESET}\""
    
    echo "$script_content"
}

# =============================================================================
# Main Initialization Logic
# =============================================================================

main() {
    info "Starting Shell Environment Optimization..."
    
    # Create configuration directory
    if [[ ! -d "$CONFIG_DIR" ]]; then
        info "Creating configuration directory: $CONFIG_DIR"
        mkdir -p "$CONFIG_DIR"
    fi
    
    # Generate and write init script
    info "Generating initialization script: $INIT_SCRIPT"
    generate_init_script > "$INIT_SCRIPT"
    chmod +x "$INIT_SCRIPT"
    success "Init script created"
    
    # Detect shell type
    local shell_type=""
    if [[ -n "$ZSH_VERSION" ]]; then
        shell_type="zsh"
    else
        shell_type="bash"
    fi
    
    info "Detected shell: $shell_type"
    
    # Backup existing shell config
    if [[ -f "$SHELL_CONFIG_FILE" ]]; then
        local backup_file="$SHELL_CONFIG_FILE$BACKUP_SUFFIX"
        info "Backing up existing shell config..."
        cp "$SHELL_CONFIG_FILE" "$backup_file"
        success "Backup created: $backup_file"
    fi
    
    # Add source directive to shell config
    info "Updating shell configuration..."
    local source_line="source \"$INIT_SCRIPT\""
    
    if ! grep -q "source.*init.sh" "$SHELL_CONFIG_FILE" 2>/dev/null; then
        echo "" >> "$SHELL_CONFIG_FILE"
        echo "# ==========================" >> "$SHELL_CONFIG_FILE"
        echo "# Shell Environment Optimizer" >> "$SHELL_CONFIG_FILE"
        echo "# ==========================" >> "$SHELL_CONFIG_FILE"
        echo "$source_line" >> "$SHELL_CONFIG_FILE"
        success "Added source directive to $SHELL_CONFIG_FILE"
    else
        warn "Source directive already exists in $SHELL_CONFIG_FILE"
    fi
    
    # Set environment variables immediately
    export CLICOLOR=1
    export LSCOLORS='ExFxBxDxCxegedabagacad'
    
    # Display summary
    echo ""
    info "=== Optimization Complete ==="
    info "Configuration directory: $CONFIG_DIR"
    info "Init script: $INIT_SCRIPT"
    info "Shell config: $SHELL_CONFIG_FILE"
    echo ""
    info "Available functions:"
    echo "  - enhanced_ls    : Enhanced directory listing with summary"
    echo "  - smart_cd       : Smart directory navigation with fuzzy matching"
    echo "  - quick_find     : Fast file search with preview"
    echo "  - qmkcd          : Create directory and enter it"
    echo "  - ftree          : Lightweight tree view"
    echo "  - qgrep          : Quick recursive grep"
    echo ""
    info "To apply changes, run: source $SHELL_CONFIG_FILE"
}

# Run main function
main "$@"