#!/bin/bash
# Build Configuration Generator

# Configuration variables
PROJECT_NAME="${PROJECT_NAME:-myproject}"
PROJECT_TYPE="${PROJECT_TYPE:-generic}"
BUILD_DIR="build"
SOURCES="src"
INCLUDES="include"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print status messages
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to generate Makefile based on project type
generate_makefile() {
    local ptype="$1"
    local compiler="${COMPILER:-gcc}"
    local flags="${CFLAGS:--Wall -Wextra -g}"
    
    print_status "Generating Makefile for project type: ${ptype}"
    
    cat > Makefile << EOF
# Makefile for ${PROJECT_NAME}
# Generated by Build Configuration Generator

CC = ${compiler}
CFLAGS = ${flags}
LDFLAGS = -lm

BUILD_DIR = ${BUILD_DIR}
SRC_DIR = ${SOURCES}
INC_DIR = ${INCLUDES}

TARGET = ${PROJECT_NAME}

# Source files based on project type
ifeq (${ptype}, library)
    SRCS = \$(SRC_DIR)/main.c \$(SRC_DIR)/module.c
    OBJS = \$(patsubst \$(SRC_DIR)/%%.c,\$(BUILD_DIR)/%%.o,\$(SRCS))
    LIB_NAME = lib\$(TARGET).a
else ifeq (${ptype}, executable)
    SRCS = \$(SRC_DIR)/main.c \$(SRC_DIR)/utils.c
    OBJS = \$(patsubst \$(SRC_DIR)/%%.c,\$(BUILD_DIR)/%%.o,\$(SRCS))
else
    SRCS = \$(SRC_DIR)/*.c
    OBJS = \$(patsubst \$(SRC_DIR)/%%.c,\$(BUILD_DIR)/%%.o,\$(SRCS))
endif

.PHONY: all build test install clean

all: build

build: \$(OBJS)
	@echo "Linking \$(TARGET)..."
	\$(CC) \$(OBJS) -o \$(TARGET) \$(LDFLAGS)

\$(BUILD_DIR)/%%.o: \$(SRC_DIR)/%%.c | \$(BUILD_DIR)
	@echo "Compiling \$<..."
	\$(CC) \$(CFLAGS) -I\$(INC_DIR) -c \$< -o \$@

\$(BUILD_DIR):
	@mkdir -p \$(BUILD_DIR)

test: build
	@echo "Running tests..."
	./\$(TARGET) --test

install: build
	@echo "Installing \$(TARGET)..."
	cp \$(TARGET) /usr/local/bin/

clean:
	rm -rf \$(BUILD_DIR) \$(TARGET)
EOF
    
    print_status "Makefile created successfully"
}

# Function to create CMakeLists.txt if CMake is available
create_cmake() {
    local ptype="$1"
    
    if ! command -v cmake &> /dev/null; then
        print_warning "CMake not detected. Skipping CMakeLists.txt generation"
        return 1
    fi
    
    print_status "Generating CMakeLists.txt for project type: ${ptype}"
    
    cat > CMakeLists.txt << EOF
cmake_minimum_required(VERSION 3.10)
project(${PROJECT_NAME})

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

# Project type specific configuration
if(${ptype} STREQUAL "library")
    add_library(${PROJECT_NAME} STATIC
        ${SOURCES}/main.c
        ${SOURCES}/module.c
    )
elseif(${ptype} STREQUAL "executable")
    add_executable(${PROJECT_NAME}
        ${SOURCES}/main.c
        ${SOURCES}/utils.c
    )
else
    add_executable(${PROJECT_NAME}
        \${CMAKE_CURRENT_SOURCE_DIR}/${SOURCES}/*.c
    )
endif()

target_include_directories(${PROJECT_NAME} PRIVATE ${INCLUDES})

# Enable testing
enable_testing()
add_test(NAME UnitTests COMMAND ${PROJECT_NAME} --test)

# Installation rules
install(TARGETS ${PROJECT_NAME}
    RUNTIME DESTINATION bin
    LIBRARY DESTINATION lib
    ARCHIVE DESTINATION lib
)
EOF
    
    print_status "CMakeLists.txt created successfully"
    return 0
}

# Function to setup the project structure
setup_project() {
    local ptype="$1"
    
    print_status "Setting up project structure for ${PROJECT_NAME}"
    
    # Create directory structure
    mkdir -p "${SOURCES}" "${INCLUDES}" "${BUILD_DIR}"
    
    # Create placeholder source files based on type
    case "${ptype}" in
        library)
            echo "int main() { return 0; }" > "${SOURCES}/main.c"
            echo "int module_func() { return 42; }" > "${SOURCES}/module.c"
            ;;
        executable)
            echo '#include <stdio.h>
int main() { printf("Hello from %s!\n", "'${PROJECT_NAME}'"); return 0; }' > "${SOURCES}/main.c"
            echo "void utils_help() { printf('Help message\n'); }" > "${SOURCES}/utils.c"
            ;;
        *)
            echo '#include <stdio.h>
int main() { printf("Hello from %s!\n", "'${PROJECT_NAME}'"); return 0; }' > "${SOURCES}/main.c"
            ;;
    esac
    
    # Create basic header file
    echo "// Header for ${PROJECT_NAME}" > "${INCLUDES}/${PROJECT_NAME}.h"
    
    # Create setup.sh script
    cat > setup.sh << 'SETUP_EOF'
#!/bin/bash
# Setup script for local configuration
# Generated by Build Configuration Generator

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Set environment variables
export PROJECT_ROOT="${SCRIPT_DIR}"
export BUILD_TYPE="debug"

# Check for required tools
check_requirements() {
    local missing=()
    for tool in gcc make; do
        if ! command -v "$tool" &> /dev/null; then
            missing+=("$tool")
        fi
    done
    
    if [ ${#missing[@]} -gt 0 ]; then
        echo "Missing required tools: ${missing[*]}"
        return 1
    fi
    return 0
}

# Main setup routine
main() {
    if ! check_requirements; then
        echo "Please install the missing tools and try again."
        exit 1
    fi
    
    echo "Project setup complete!"
    echo "Root directory: $PROJECT_ROOT"
    echo "Build type: $BUILD_TYPE"
}

main "$@"
SETUP_EOF

    chmod +x setup.sh
    
    # Add setup.sh to .gitignore if not already present
    if [ -f ".gitignore" ]; then
        if ! grep -q "setup.sh" .gitignore; then
            echo "setup.sh" >> .gitignore
            print_status "Added setup.sh to .gitignore"
        fi
    else
        echo "setup.sh" > .gitignore
        print_status "Created .gitignore with setup.sh"
    fi
    
    print_status "Project structure setup complete"
}

# Function to display usage information
show_usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS]

Options:
    --type TYPE       Project type (library, executable, generic) [default: generic]
    --name NAME       Project name [default: myproject]
    --help            Show this help message

Examples:
    $(basename "$0") --type library --name mylib
    $(basename "$0") --type executable

Environment Variables:
    PROJECT_NAME      Override project name
    PROJECT_TYPE      Override project type
    COMPILER          C compiler to use (default: gcc)
    CFLAGS            Compiler flags (default: -Wall -Wextra -g)
EOF
}

# Main execution
main() {
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --type)
                PROJECT_TYPE="$2"
                shift 2
                ;;
            --name)
                PROJECT_NAME="$2"
                shift 2
                ;;
            --help)
                show_usage
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
    
    print_status "Build Configuration Generator"
    print_status "Project: ${PROJECT_NAME} (Type: ${PROJECT_TYPE})"
    echo "----------------------------------------"
    
    # Execute generation functions
    generate_makefile "${PROJECT_TYPE}"
    create_cmake "${PROJECT_TYPE}"
    setup_project "${PROJECT_TYPE}"
    
    echo "----------------------------------------"
    print_status "Configuration generation complete!"
}

# Run main function
main "$@"