#!/bin/bash
# Build Configuration Generator

# Default values
PROJECT_ROOT="."
PROJECT_TYPE="application"
PROJECT_NAME="myproject"

# Function to display usage information
show_usage() {
    echo "Usage: $0 [OPTIONS] [PROJECT_ROOT]"
    echo ""
    echo "Build Configuration Generator - Creates build configuration files for projects"
    echo ""
    echo "OPTIONS:"
    echo "  --type TYPE     Set project type (library|application|executable)"
    echo "                  Default: application"
    echo "  --name NAME     Set project name"
    echo "                  Default: myproject"
    echo "  --help          Show this help message"
    echo ""
    echo "Arguments:"
    echo "  PROJECT_ROOT    Root directory of the project (default: current directory)"
}

# Function to generate Makefile
generate_makefile() {
    local project_root="$1"
    local project_type="$2"
    local project_name="$3"
    
    local makefile_content='
# Auto-generated Makefile
# Build Configuration Generator

# Compiler settings
CC = gcc
CXX = g++
CFLAGS = -Wall -Wextra -O2
CXXFLAGS = -Wall -Wextra -O2
LDFLAGS =

# Directories
SRCDIR = src
OBJDIR = obj
BINDIR = bin

# Source files
SRCS = $(wildcard $(SRCDIR)/*.c)
OBJS = $(SRCS:$(SRCDIR)/%.c=$(OBJDIR)/%.o)

# Project name
TARGET = $(PROJECT_NAME)

# Default target
.PHONY: all
all: build

# Build target
.PHONY: build
build: $(OBJDIR) $(BINDIR) $(BINDIR)/$(TARGET)
	@echo "Build complete: $(BINDIR)/$(TARGET)"

# Create directories
$(OBJDIR):
	mkdir -p $(OBJDIR)

$(BINDIR):
	mkdir -p $(BINDIR)

# Build target
$(BINDIR)/$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^

# Compile source files
$(OBJDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

# Test target
.PHONY: test
test: build
	@echo "Running tests..."
	./$(BINDIR)/$(TARGET) --test

# Install target
.PHONY: install
install: build
	@echo "Installing to /usr/local/bin..."
	cp $(BINDIR)/$(TARGET) /usr/local/bin/

# Clean target
.PHONY: clean
clean:
	rm -rf $(OBJDIR) $(BINDIR)

# Help target
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  build   - Build the project"
	@echo "  test    - Run tests"
	@echo "  install - Install the project"
	@echo "  clean   - Remove build artifacts"
	@echo "  help    - Show this help message"
'
    
    # Replace PROJECT_NAME placeholder
    makefile_content="${makefile_content//\$(PROJECT_NAME)/${project_name}}"
    
    echo "$makefile_content" > "${project_root}/Makefile"
    echo "✓ Generated Makefile in ${project_root}"
}

# Function to create CMakeLists.txt
create_cmake() {
    local project_root="$1"
    local project_type="$2"
    local project_name="$3"
    
    # Check if CMake is installed
    if ! command -v cmake &> /dev/null; then
        echo "⚠ CMake not detected. Skipping CMakeLists.txt generation."
        return 1
    fi
    
    local cmake_content='
cmake_minimum_required(VERSION 3.10)
project(PROJECT_NAME VERSION 1.0.0 LANGUAGES C CXX)

# C++ Standard
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Build type
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()

# Compiler flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")

# Source files
set(SOURCES
    src/main.c
)

# Include directories
include_directories(include)

# Add executable
add_executable(${PROJECT_NAME} ${SOURCES})

# Test target
enable_testing()
add_test(NAME unit_tests COMMAND ${PROJECT_NAME} --test)

# Install target
install(TARGETS ${PROJECT_NAME} DESTINATION bin)

# Build options
option(BUILD_SHARED_LIBS "Build shared libraries" ON)
option(WITH_TESTS "Build tests" ON)
'
    
    # Replace PROJECT_NAME placeholder
    cmake_content="${cmake_content//PROJECT_NAME/${project_name}}"
    
    echo "$cmake_content" > "${project_root}/CMakeLists.txt"
    echo "✓ Generated CMakeLists.txt in ${project_root}"
    return 0
}

# Function to setup project
setup_project() {
    local project_root="$1"
    local project_type="$2"
    
    local setup_script='
#!/bin/bash
# Project Setup Script
# Auto-generated by Build Configuration Generator

set -e

echo "Setting up project..."

# Check for required tools
check_requirements() {
    local missing=()
    
    if ! command -v gcc &> /dev/null; then
        missing+=("gcc")
    fi
    
    if ! command -v make &> /dev/null; then
        missing+=("make")
    fi
    
    if [ ${#missing[@]} -gt 0 ]; then
        echo "Missing required tools: ${missing[*]}"
        echo "Please install them and run setup.sh again."
        exit 1
    fi
    
    echo "✓ All requirements met"
}

# Initialize git repository
init_git() {
    if [ ! -d ".git" ]; then
        git init
        echo "✓ Initialized git repository"
    else
        echo "✓ Git repository already exists"
    fi
}

# Create necessary directories
create_directories() {
    local dirs=("src" "include" "tests" "docs" "build")
    
    for dir in "${dirs[@]}"; do
        if [ ! -d "$dir" ]; then
            mkdir -p "$dir"
            echo "✓ Created directory: $dir"
        fi
    done
}

# Create sample source file
create_sample_source() {
    if [ ! -f "src/main.c" ]; then
        cat > src/main.c << '\''SRCEOF'\''
#include <stdio.h>

int main(int argc, char *argv[]) {
    printf("Hello, World!\n");
    
    if (argc > 1 && strcmp(argv[1], "--test") == 0) {
        printf("Tests passed!\n");
        return 0;
    }
    
    return 0;
}
SRCEOF
        echo "✓ Created sample source file: src/main.c"
    fi
}

# Main setup routine
main() {
    echo "========================================="
    echo "       Project Setup Script"
    echo "========================================="
    echo ""
    
    check_requirements
    echo ""
    
    create_directories
    echo ""
    
    create_sample_source
    echo ""
    
    init_git
    echo ""
    
    echo "========================================="
    echo "       Setup Complete!"
    echo "========================================="
    echo ""
    echo "You can now build your project with:"
    echo "  make              - Build the project"
    echo "  make test         - Run tests"
    echo "  make install      - Install the project"
    echo ""
}

main "$@"
'
    
    echo "$setup_script" > "${project_root}/setup.sh"
    chmod +x "${project_root}/setup.sh"
    echo "✓ Generated setup.sh in ${project_root}"
}

# Function to add file to .gitignore
add_to_gitignore() {
    local project_root="$1"
    local file_to_ignore="$2"
    local gitignore="${project_root}/.gitignore"
    
    # Create .gitignore if it doesn't exist
    if [ ! -f "$gitignore" ]; then
        touch "$gitignore"
        echo "✓ Created .gitignore in ${project_root}"
    fi
    
    # Check if file is already in .gitignore
    if ! grep -q "^${file_to_ignore}$" "$gitignore" 2>/dev/null; then
        echo "${file_to_ignore}" >> "$gitignore"
        echo "✓ Added ${file_to_ignore} to .gitignore"
    else
        echo "✓ ${file_to_ignore} already in .gitignore"
    fi
}

# Main function
main() {
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --type)
                PROJECT_TYPE="$2"
                shift 2
                ;;
            --name)
                PROJECT_NAME="$2"
                shift 2
                ;;
            --help)
                show_usage
                exit 0
                ;;
            -*)
                echo "Error: Unknown option $1"
                show_usage
                exit 1
                ;;
            *)
                PROJECT_ROOT="$1"
                shift
                ;;
        esac
    done
    
    # Validate project type
    case $PROJECT_TYPE in
        library|application|executable)
            ;;
        *)
            echo "Warning: Unknown project type '$PROJECT_TYPE'. Using 'application'."
            PROJECT_TYPE="application"
            ;;
    esac
    
    # Change to project root
    if [ -d "$PROJECT_ROOT" ]; then
        cd "$PROJECT_ROOT" || exit 1
    else
        echo "Error: Project root directory '$PROJECT_ROOT' does not exist"
        exit 1
    fi
    
    echo "========================================="
    echo "    Build Configuration Generator"
    echo "========================================="
    echo ""
    echo "Project Root: $(pwd)"
    echo "Project Type: $PROJECT_TYPE"
    echo "Project Name: $PROJECT_NAME"
    echo ""
    
    # Generate configuration files
    generate_makefile "$(pwd)" "$PROJECT_TYPE" "$PROJECT_NAME"
    create_cmake "$(pwd)" "$PROJECT_TYPE" "$PROJECT_NAME"
    setup_project "$(pwd)" "$PROJECT_TYPE"
    add_to_gitignore "$(pwd)" "setup.sh"
    
    echo ""
    echo "========================================="
    echo "    Configuration Complete!"
    echo "========================================="
}

# Run main function with all arguments
main "$@"