#!/bin/bash
# Build Configuration Generator

# Configuration variables
readonly SCRIPT_NAME="BuildConfigGen"
readonly VERSION="1.0.0"
readonly DEFAULT_TYPE="generic"

# Project metadata storage
declare -A PROJECT_INFO

# Color output helpers
colr() {
    local codes=(
        ""          # $0
        "\033[01m"  # $1 - bold
        "\033[033m" # $2 - yellow
        "\033[035m" # $3 - magenta
    )
    echo -e "${codes[$1]}${2:-}"
}

# Display usage information
show_help() {
    cat << EOF
Usage: ${SCRIPT_NAME} [OPTIONS] [PROJECT_DIR]

Generate build configuration files for software projects.

OPTIONS:
    --type TYPE      Project type (${DEFAULT_TYPE}, python, go, rust)
    --name NAME      Project name (default: directory name)
    --version VER    Project version (default: ${VERSION})
    --help           Show this help message

EXAMPLES:
    ${SCRIPT_NAME} .
    ${SCRIPT_NAME} --type python --name myproject ./src
    ${SCRIPT_NAME} --type rust /path/to/project

EOF
}

# Generate Makefile with project-specific targets
generate_makefile() {
    local ptype="${1:-${DEFAULT_TYPE}}"
    local pname="${2:-${PROJECT_INFO[name]}}"
    local pver="${3:-${PROJECT_INFO[version]}}"
    local out="${4:-Makefile}"

    cat > "${out}" << MAKEFILE_EOF
# Generated by ${SCRIPT_NAME} v${VERSION}
# Project: ${pname} v${pver}

.PHONY: all build test clean install check help

# Compiler settings
CC := gcc
CFLAGS := -Wall -Wextra -g

# Project variables
PROJECT := ${pname}
VERSION := ${pver}
BUILD_DIR := build
SRC_DIR := src

# Source files detection
ifeq (\$(CTYPE), python)
    SOURCES := \$(shell find src -name "*.py")
else ifeq (\$(CTYPE), go)
    SOURCES := \$(shell find src -name "*.go")
else ifeq (\$(CTYPE), rust)
    SOURCES := \$(shell find src -name "*.rs")
else
    SOURCES := \$(shell find src -name "*.c" -o -name "*.cpp")
endif

# Default target
all: build

# Build target
build:
\techo "Building \$(PROJECT) v\$(VERSION)..."
\techo "Project type: \$(CTYPE)"
\tmkdir -p \$(BUILD_DIR)
\t@if [ -f CMakeLists.txt ]; then \
\t\techo "Using CMake build system..."; \
\t\tcmake --build \$(BUILD_DIR) --target all; \
\telse \
\t\techo "Using Make build system..."; \
\t\t\$(CC) \$(CFLAGS) -o \$(BUILD_DIR)/\$(PROJECT) \$(SOURCES); \
\tfi

# Test target
test: build
\techo "Running tests..."
\t@if [ -f CMakeLists.txt ]; then \
\t\tctest --test-dir \$(BUILD_DIR); \
\telse \
\t\t./\$(BUILD_DIR)/\$(PROJECT) --test; \
\tfi

# Install target
install: build
\techo "Installing \$(PROJECT)..."
\tcp -r \$(BUILD_DIR)/\$(PROJECT) /usr/local/bin/
\tchmod +x /usr/local/bin/\$(PROJECT)

# Clean target
clean:
\techo "Cleaning build artifacts..."
\trm -rf \$(BUILD_DIR)
\tfind . -name "*.o" -delete
\tfind . -name "*.pyc" -delete

# Check dependencies
check:
\techo "Checking build dependencies..."
\twhich \$(CC) > /dev/null || { echo "Error: \$(CC) not found"; exit 1; }
\twhich cmake > /dev/null || echo "Warning: cmake not found"

# Help target
help:
\t@echo "Available targets:"
\t@echo "  all     - Build the project (default)"
\t@echo "  build   - Compile the project"
\t@echo "  test    - Run tests"
\t@echo "  clean   - Remove build artifacts"
\t@echo "  install - Install to system"
\t@echo "  check   - Verify dependencies"
\t@echo "  help    - Show this message"
MAKEFILE_EOF

    echo "  [✓] Created Makefile"
}

# Create CMake configuration when available
create_cmake() {
    local ptype="${1:-${DEFAULT_TYPE}}"
    local pname="${2:-${PROJECT_INFO[name]}}"
    local pver="${3:-${PROJECT_INFO[version]}}"

    if ! command -v cmake &>/dev/null; then
        echo "  [!] CMake not found, skipping CMakeLists.txt generation"
        return 1
    fi

    cat > "CMakeLists.txt" << CMAKE_EOF
cmake_minimum_required(VERSION 3.10)

project(${pname}
    VERSION ${pver}
    DESCRIPTION "Generated project configuration"
    LANGUAGES C
)

# Set build type if not specified
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type" FORCE)
endif()

# Compiler flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra")
set(CMAKE_C_FLAGS_DEBUG "-g -O0")
set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")

# Project type specific settings
if("${ptype}" STREQUAL "python")
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    enable_testing()
    add_custom_target(test
        COMMAND Python3::Interpreter -m unittest discover
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    )
elseif("${ptype}" STREQUAL "go")
    find_program(GO_EXECUTABLE go)
    if(GO_EXECUTABLE)
        enable_testing()
        add_custom_target(build
            COMMAND \${GO_EXECUTABLE} build -o \${CMAKE_BINARY_DIR}/\${PROJECT_NAME} ./...
        )
        add_custom_target(test
            COMMAND \${GO_EXECUTABLE} test ./...
        )
    endif()
elseif("${ptype}" STREQUAL "rust")
    find_program(RUSTC_EXECUTABLE rustc)
    if(RUSTC_EXECUTABLE)
        enable_testing()
        add_custom_target(build
            COMMAND cargo build --release
        )
        add_custom_target(test
            COMMAND cargo test
        )
    endif()
else()
    # Default C/C++ project
    file(GLOB SOURCES "src/*.c" "src/*.cpp")
    add_executable(${pname} \${SOURCES})
    target_include_directories(${pname} PRIVATE include)
    enable_testing()
    add_subdirectory(tests EXCLUDE_FROM_ALL)
endif()

# Installation rules
install(TARGETS ${pname} DESTINATION bin)
CMAKE_EOF

    echo "  [✓] Created CMakeLists.txt"
    return 0
}

# Initialize project structure and configuration
setup_project() {
    local ptype="${1:-${DEFAULT_TYPE}}"
    local pname="${2:-${PROJECT_INFO[name]}}"
    local pver="${3:-${PROJECT_INFO[version]}}"

    cat > "setup.sh" << SETUP_EOF
#!/bin/bash
# Auto-generated setup script for ${pname} v${pver}
# Type: ${ptype}

set -e

PROJECT_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
export PROJECT_ROOT

echo "Setting up ${pname}..."

# Set project type
export PROJECT_TYPE="${ptype}"

# Initialize submodules if .gitmodules exists
if [ -f .gitmodules ]; then
    git submodule update --init --recursive
fi

# Type-specific setup
case "\${PROJECT_TYPE}" in
    python)
        echo "Creating virtual environment..."
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt 2>/dev/null || true
        ;;
    go)
        echo "Fetching Go dependencies..."
        go mod download
        go mod tidy
        ;;
    rust)
        echo "Checking Rust toolchain..."
        cargo build --quiet
        ;;
    *)
        echo "Generic setup complete"
        ;;
esac

echo "Setup complete for ${pname}"
SETUP_EOF

    chmod +x "setup.sh"
    echo "  [✓] Created setup.sh"

    # Add to .gitignore if not present
    if [ -f ".gitignore" ]; then
        if ! grep -q "^setup.sh$" ".gitignore"; then
            echo "setup.sh" >> .gitignore
            echo "  [✓] Added setup.sh to .gitignore"
        fi
    else
        cat > .gitignore << GITIGNORE_EOF
# Build artifacts
build/
*.o
*.pyc
__pycache__/
*.so

# IDE
.idea/
.vscode/
*.swp
*.swo

# Local configuration
setup.sh
.env
GITIGNORE_EOF
        echo "  [✓] Created .gitignore with setup.sh entry"
    fi
}

# Parse command line arguments
parse_args() {
    local project_dir="."
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            --type)
                PROJECT_INFO[type]="$2"
                shift 2
                ;;
            --name)
                PROJECT_INFO[name]="$2"
                shift 2
                ;;
            --version)
                PROJECT_INFO[version]="$2"
                shift 2
                ;;
            --help)
                show_help
                exit 0
                ;;
            *)
                project_dir="$1"
                shift
                ;;
        esac
    done

    # Set defaults if not specified
    PROJECT_INFO[type]="${PROJECT_INFO[type]:-${DEFAULT_TYPE}}"
    PROJECT_INFO[name]="${PROJECT_INFO[name]:-$(basename "$project_dir")}"
    PROJECT_INFO[version]="${PROJECT_INFO[version]:-${VERSION}}"

    echo "$project_dir"
}

# Main execution
main() {
    local target_dir
    target_dir=$(parse_args "$@")

    if [ ! -d "$target_dir" ]; then
        echo "Error: Directory '$target_dir' does not exist"
        exit 1
    fi

    echo "=== ${SCRIPT_NAME} v${VERSION} ==="
    echo "Project: ${PROJECT_INFO[name]} v${PROJECT_INFO[version]}"
    echo "Type: ${PROJECT_INFO[type]}"
    echo "Target: $target_dir"
    echo ""

    cd "$target_dir" || exit 1

    # Generate configuration files
    generate_makefile "${PROJECT_INFO[type]}" "${PROJECT_INFO[name]}" "${PROJECT_INFO[version]}"
    create_cmake "${PROJECT_INFO[type]}" "${PROJECT_INFO[name]}" "${PROJECT_INFO[version]}"
    setup_project "${PROJECT_INFO[type]}" "${PROJECT_INFO[name]}" "${PROJECT_INFO[version]}"

    echo ""
    echo "Configuration generation complete!"
}

# Run main function
main "$@"