#!/bin/bash
# Build Configuration Generator

bcg_project_type="default"
bcg_project_dir="."
bcg_verbose="false"

bcg_print_status() {
    local msg="$1"
    if [[ "$bcg_verbose" == "true" ]]; then
        echo -e "\033[1;36m[INFO]\033[0m $msg"
    fi
}

bcg_parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --type)
                bcg_project_type="$2"
                shift 2
                ;;
            --dir)
                bcg_project_dir="$2"
                shift 2
                ;;
            --verbose)
                bcg_verbose="true"
                shift
                ;;
            *)
                echo "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

bcg_check_cmake() {
    command -v cmake &> /dev/null
}

bcg_generate_makefile() {
    local ptype="$1"
    local pdir="$2"
    
    bcd_makefile_content="# Makefile - Auto-generated by Build Configuration Generator
# Project Type: $ptype

CC := gcc
CFLAGS := -Wall -Wextra -O2

SRCS := $(wildcard *.c)
OBJS := \$(SRCS:.c=.o)
TARGET := project

.PHONY: build test install clean

build: \$(OBJS)
\t\$(CC) \$(CFLAGS) -o \$(TARGET) \$(OBJS)

\$(OBJS): \$(SRCS)
\t\$(CC) \$(CFLAGS) -c \$< -o \$@

test: build
\techo \"Running tests...\"
\t./test_runner

install: build
\tcp \$(TARGET) /usr/local/bin/

clean:
\trm -f \$(OBJS) \$(TARGET)
"
    echo "$bcd_makefile_content" > "$pdir/Makefile"
    bcg_print_status "Generated Makefile in $pdir"
}

bcg_create_cmake() {
    local ptype="$1"
    local pdir="$2"
    
    if ! bcg_check_cmake; then
        bcg_print_status "CMake not detected, skipping CMakeLists.txt generation"
        return 1
    fi
    
    bcd_cmake_content="cmake_minimum_required(VERSION 3.10)
project(build_project)

set(CMAKE_C_STANDARD 11)

add_executable(project main.c)

if(MSVC)
    target_compile_options(project PRIVATE /W4)
else()
    target_compile_options(project PRIVATE -Wall -Wextra)
endif()

enable_testing()
add_test(NAME unit_tests COMMAND ./test_runner)
"
    echo "$bcd_cmake_content" > "$pdir/CMakeLists.txt"
    bcg_print_status "Generated CMakeLists.txt in $pdir"
}

bcg_setup_project() {
    local ptype="$1"
    local pdir="$2"
    
    bcd_setup_content="#!/bin/bash
# Setup script for project: $ptype

set -e

echo \"Setting up project environment...\"

if [ -f \"Makefile\" ]; then
    echo \"Running make build...\"
    make build
fi

if [ -f \"CMakeLists.txt\" ]; then
    echo \"Running cmake configuration...\"
    cmake -B build .
    cmake --build build
fi

echo \"Setup complete!\"
"
    echo "$bcd_setup_content" > "$pdir/setup.sh"
    chmod +x "$pdir/setup.sh"
    bcg_print_status "Generated setup.sh in $pdir"
}

bcg_add_to_gitignore() {
    local pdir="$1"
    local pattern="$2"
    
    if [[ ! -f "$pdir/.gitignore" ]]; then
        echo "# Auto-generated .gitignore" > "$pdir/.gitignore"
    fi
    
    if ! grep -q "^$pattern$" "$pdir/.gitignore"; then
        echo "$pattern" >> "$pdir/.gitignore"
        bcg_print_status "Added $pattern to .gitignore"
    fi
}

bcg_main() {
    bcg_parse_args "$@"
    
    bcg_print_status "Building configuration for type: $bcg_project_type"
    
    case "$bcg_project_type" in
        "c")
            bcg_generate_makefile "c" "$bcg_project_dir"
            bcg_create_cmake "c" "$bcg_project_dir"
            ;;
        "cpp")
            bcg_generate_makefile "cpp" "$bcg_project_dir"
            bcg_create_cmake "cpp" "$bcg_project_dir"
            ;;
        "python")
            bcg_generate_makefile "python" "$bcg_project_dir"
            ;;
        *)
            bcg_generate_makefile "default" "$bcg_project_dir"
            bcg_create_cmake "default" "$bcg_project_dir"
            ;;
    esac
    
    bcg_setup_project "$bcg_project_type" "$bcg_project_dir"
    bcg_add_to_gitignore "$bcg_project_dir" "setup.sh"
}

bcg_main "$@"