# Project Initialization Tool

import os
import sys
from pathlib import Path
from datetime import datetime

def create_structure(project_name):
    """Create the directory structure for the project."""
    base_path = Path(project_name)
    
    directories = [
        base_path,
        base_path / "src",
        base_path / "src" / project_name.replace("-", "_"),
        base_path / "tests",
        base_path / "docs",
        base_path / "config"
    ]
    
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
    
    print(f"✓ Directory structure created for '{project_name}'")
    return base_path

def write_config(project_name, base_path):
    """Generate configuration files and requirements."""
    package_name = project_name.replace("-", "_")
    
    # Generate requirements.txt
    requirements_content = """# Project Dependencies
# Auto-generated by Project Initialization Tool

# Core
flask>=2.0.0
requests>=2.28.0
python-dotenv>=0.19.0

# Development
pytest>=7.0.0
pytest-cov>=3.0.0
black>=22.0.0
flake8>=4.0.0

# Utilities
click>=8.0.0
"""
    
    requirements_path = base_path / "requirements.txt"
    with open(requirements_path, 'w', encoding='utf-8') as f:
        f.write(requirements_content)
    
    # Generate config.py with initialization timestamp
    config_content = f"""# Configuration file for {project_name}
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

import os
from pathlib import Path

class Config:
    DEBUG = True
    SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-key-change-in-production')
    BASE_DIR = Path(__file__).resolve().parent.parent
    
    DATABASE_URL = os.environ.get('DATABASE_URL', 'sqlite:///app.db')
    CACHE_DIR = BASE_DIR / 'cache'
    
    VERSION = '0.0.0'
    UPDATE_CHECK_INTERVAL = 3600
    
    @classmethod
    def update_version(cls, new_version):
        cls.VERSION = new_version
        print(f'Version updated to: {{new_version}}')
"""
    
    config_path = base_path / "config.py"
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(config_content)
    
    # Create __init__.py with auto-update feature
    init_content = f"""# Auto-generated __init__.py for {package_name}
# Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

import os
import json
from pathlib import Path

__version__ = '0.0.0'
__author__ = 'Project Initialization Tool'

AUTO_UPDATE_PATH = os.path.join(os.path.dirname(__file__), '.update_info.json')

def check_for_update():
    \"\"\"Check if a newer version is available.
    
    Returns:
        bool: True if update is available, False otherwise
    \"\"\"
    try:
        if os.path.exists(AUTO_UPDATE_PATH):
            with open(AUTO_UPDATE_PATH, 'r') as f:
                update_info = json.load(f)
            current_version = update_info.get('current_version', '0.0.0')
            if current_version != __version__:
                print(f"Update available: {__version__} -> {current_version}")
                return True
    except Exception:
        pass
    return False

def update_package():
    \"\"\"Update package version information.\"\"\"
    update_data = {
        'current_version': __version__,
        'last_checked': str(datetime.now())
    }
    with open(AUTO_UPDATE_PATH, 'w') as f:
        json.dump(update_data, f, indent=2)
    print("Package updated successfully")

def __auto_init__():
    \"\"\"Automatic initialization on module import.\"\"\"
    check_for_update()
    update_package()

__auto_init__()
"""
    
    init_path = base_path / "src" / package_name / "__init__.py"
    with open(init_path, 'w', encoding='utf-8') as f:
        f.write(init_content)
    
    # Create __init__.py for src directory
    src_init = base_path / "src" / "__init__.py"
    with open(src_init, 'w', encoding='utf-8') as f:
        f.write("# Source directory\n")
    
    # Create __init__.py for tests directory
    tests_init = base_path / "tests" / "__init__.py"
    with open(tests_init, 'w', encoding='utf-8') as f:
        f.write("# Tests directory\n")
    
    # Create __init__.py for docs directory
    docs_init = base_path / "docs" / "__init__.py"
    with open(docs_init, 'w', encoding='utf-8') as f:
        f.write("# Documentation directory\n")
    
    # Create __init__.py for config directory
    config_init = base_path / "config" / "__init__.py"
    with open(config_init, 'w', encoding='utf-8') as f:
        f.write("# Configuration directory\n")
    
    # Create .update_info.json for auto-update feature
    update_info_path = base_path / ".update_info.json"
    with open(update_info_path, 'w', encoding='utf-8') as f:
        json.dump({
            "last_check": datetime.now().isoformat(),
            "current_version": "0.0.0"
        }, f, indent=2)
    
    print("✓ Configuration files generated")
    return base_path

def setup_git(project_name, base_path):
    """Set up git repository and ignore file."""
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
*.egg-info/
dist/
build/
.pytest_cache/
.coverage
htmlcov/
mypy/

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Project specific
.env
*.log
cache/
*.db
"""
    
    gitignore_path = base_path / ".gitignore"
    with open(gitignore_path, 'w', encoding='utf-8') as f:
        f.write(gitignore_content)
    
    # Create README.md
    readme_content = f"""# {project_name}

A Python project initialized by the Project Initialization Tool.

## Installation
