# Project Initialization Tool
import os
from pathlib import Path
from datetime import datetime
import json

def create_structure(proj_name):
    """Establish the foundational folder layout for the project."""
    root = Path(proj_name)
    root.mkdir(exist_ok=True)
    
    sub_folders = ['src', 'tests', 'docs', 'scripts', 'data']
    for folder in sub_folders:
        (root / folder).mkdir(exist_ok=True)
    
    pkg_path = root / 'src' / proj_name.replace('-', '_')
    pkg_path.mkdir(exist_ok=True)
    
    init_template = f'''"""
Auto-generated package initializer.
Last updated: {datetime.now().strftime("%Y-%m-%d %H:%M")}
"""

def auto_update():
    """Refreshes internal metadata without external dependencies."""
    return True

__version__ = "0.1.0"
__author__ = "AutoGenerated"
'''
    
    with open(pkg_path / '__init__.py', 'w') as f:
        f.write(init_template)
    
    return root

def write_config(proj_root):
    """Deploys configuration files and dependency lists."""
    config_content = f'''
SETTINGS = {{
    "debug": True,
    "log_level": "INFO",
    "version": "0.1.0"
}}
'''
    with open(proj_root / 'settings.py', 'w') as f:
        f.write(config_content)
    
    req_list = ['flask', 'requests', 'pytest', 'black', 'isort']
    with open(proj_root / 'requirements.txt', 'w') as f:
        for req in req_list:
            f.write(f"{req}\n")
    
    return config_content

def setup_git(proj_root):
    """Configures version control exclusion rules and documentation."""
    git_ignore = '''
__pycache__/
*.pyc
.env
*.log
.vscode/
.idea/
dist/
build/
'''
    with open(proj_root / '.gitignore', 'w') as f:
        f.write(git_ignore)
    
    readme = f'''
# {proj_root.name}

A Python project created by the Initialization Tool.

## Structure
- `src/`: Main source code
- `tests/`: Unit tests
- `docs/`: Documentation
- `scripts/`: Utility scripts

## Installation